env:
  es6: true
  browser: true
parserOptions:
    sourceType: "module"

rules:
    # padded-blocks: 0
    # func-names: 0
    # no-spaced-func: 0
    # space-before-blocks: 0
    # # space-before-function-paren: 0
    # no-return-assign: 0
    # indent: 0
    # no-console": 0
    # no-const-assign: 0
    # no-labels: 0
    brace-style: [2, "1tbs"]
    comma-style: 0
    default-case: 2
    func-style: 0
    no-floating-decimal: 2
    no-nested-ternary: 2
    no-undefined: 2
    radix: 2
    space-before-function-paren: [1, "never"]
    keyword-spacing: [2, {after: true}]
    space-before-blocks: 1
    spaced-comment: [2, "always", { exceptions: ["-"]}]
    valid-jsdoc: [1, { requireReturn: false, prefer: { return: "returns" }}]
    wrap-iife: 2
    guard-for-in: 2
    strict: [2, "global"]
    no-alert: 2
    camelcase: 1
    curly: 0
    eqeqeq: [2, "allow-null"]
    no-empty: 2
    no-use-before-define: 2
    no-obj-calls: 2
    no-unused-vars: [1, {vars: "local", args: "after-used"}]
    new-cap: 2
    no-shadow: 1
    no-invalid-regexp: 2
    comma-dangle: 0
    no-undef: 0
    no-new: 2
    no-extra-semi: 2
    no-debugger: 2
    no-caller: 1
    semi: 2
    quotes: [1, "single", "avoid-escape"]
    no-unreachable: 2
    eol-last: 1
    operator-linebreak: [1, "before", {overrides: {"?": "after", ":": "after"}}]
    max-len: 0
    no-multi-str: 1
    no-mixed-spaces-and-tabs: 1
    no-trailing-spaces: 1
    space-infix-ops: 1
    space-unary-ops: 1
    no-with: 2
    dot-notation: 1
    semi-spacing: 1
    key-spacing: [1, {beforeColon: false, afterColon: true, mode: "minimum"}]
    space-in-parens: [1, "never"]
