language: node_js
node_js:
- '5.3'
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
- npm install -g gulp
script: gulp
env:
  global:
  - secure: ODQEP77ym4YZ16RBRdZf3pi4YE8tYs83hYLTgiSGUBwB4P+nmLzNQ2P7ceu4eCy/0gIDGTyfnVjNPXPmoJovcBDOnnp+B7+TNBM6alqVNiUE0lzLjsrnVWnkf7uvWSIHSBMft6tG7c66RYFFQEDkHqTc7Hsq5K9/HrNXswNku7489cp7q7CEergdTgm1uMsdGUxmVf/knmXe29BaLx6ap3TGK7JQcTmBY68bin02HfGxubidf7pFWOrZPrCWLsuG1ZpkgaMO+a2PFPNI4tSKEe7wtHL89gN3R1qGiKi1LrAwp7OV1Xmf/K/kvadHxgobVM+5SxzFZrGyyBOwNfB4KTRdawfehRVW3VsEuxFPzVvH+LREmkXot7jGLAy3nR2i27V2WxDUaW2XyBT9hLvVSzZJa+JI5MIvAMK55U53GRDQrDonGV9jvNQETHQpjZ7Q8RG/oV9J7867pMBflFadUVT6+Giv08sRFAjY/z9KnwxTYpTGkBIoUQh7l/V+DKnihcUFAq3HBaw5rez5j1h1A1yvrWI+CWxtIpN8fD8+JmKYOHmgjFgClP/OsqgIs4PdZNct8Glr3zdRgjjwZxBbMa3/UzwKlGaLgLq80+MCNrQRb5eN8iwIh98Z3twui3ru7HiFFK0mKquA+3KlEGAkryv7Or4bRijXuJDmgARAxLg=
